database:
  host: localhost
  name: crc
  username: root
  password: ''

#If this is set to true the player will be teleported to the spawn location on join.
tptospawn: true
spawn: null

#You can find the block id's here: http://minecraft-ids.grahamedgecombe.com/
#to add a new block to the list
# First argument is the id:data type if not is mentioned just type 0
# Second argument is the point increase per block.
# for example: (without data)
#   Stone
#   - '1:0-0.0005'
#              (with data)
#   Jungle Wood Plank
#   - '1:3-0.001'
pointsperblock:
  - '1:0-0.00002'
  - '1:2-0.00004'
  - '1:4-0.00004'
  - '1:6-0.00004'
  - '4:0-0.00001'
  - '5:0-0.00002'
  - '5:1-0.00002'
  - '5:2-0.00002'
  - '5:3-0.00002'
  - '5:4-0.00002'
  - '5:5-0.00002'
  - '20:0-0.0001'
  - '22:0-0.0003'
  - '25:0-0.01'

#on this location is the tutorial spawn.
tutorialspawn: null